### ISSUE TITLE
Problema ao instalar

### ISSUE THREAD

**Issue by gjunior01** [fernandoramacciotti/nefindata#1]
Prezado,
o package nao se encontra no CRAN, e quand faço o code:
devtools::install_github('fernandoramacciotti/nefindata/R')

Está com erro e com a seguinte msg:
Erro: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`fernandoramacciotti`) and repo name (`nefindata`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by fernandoramacciotti** [comment]
@gjunior01 obrigado por reportar - de fato o link está errado.

o comando correto é `devtools::install_github('fernandoramacciotti/nefindata/R-package')`

Já corrigi no README e agora deve funcionar.
